FROM karyonfood/alpine-node-ci

COPY . /srv

ARG TESTING
ARG BRANCH
ARG VERSION
ARG COMMIT
ARG SENTRY_RELEASE

ENV TESTING=$TESTING
ENV BRANCH=$BRANCH
ENV VERSION=$VERSION
ENV COMMIT=$COMMIT
ENV SENTRY_RELEASE=$SENTRY_RELEASE

RUN yarn --frozen-lockfile --no-cache
CMD ENVIRONMENT=prod node /srv/dist/main.js
EXPOSE 9222
